name: Checks

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup PDM
      uses: pdm-project/setup-pdm@v4
    - name: Install dependencies
      run: pdm install -G lint
    - name: Lint with flake8
      run: |
        pdm run flake8 src test

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.11']
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4
    - name: Setup PDM
      uses: pdm-project/setup-pdm@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        # install dependencies
        pdm install --prod
        pdm install -G test
    - name: Test with pytest
      run: |
        pdm run coverage run --source=src/radontea -m pytest test
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
