name: Release to PyPI

on:  
  push:
    branches:
      master
    tags:
      - '*'

jobs:
  deploy:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup PDM
      uses: pdm-project/setup-pdm@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        pdm install --prod
        pdm install -G upload
    - name: Build
      run: |
        pdm build
    - name: Publish in main repo
      if: github.repository == 'RI-imaging/radontea'
      env:
        TWINE_USERNAME: ci_qpi
        TWINE_PASSWORD: ${{ secrets.PYPI_PWD }}
      run: |
        pdm run twine upload --skip-existing dist/*
